on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Workers
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires

      - name: Publish Gentle Rain Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: gentle-rain-da08
          directory: gentle-rain-da08
          command: deploy gentle-rain-da08/src/index.js  # Specify the entry point for Gentle Rain Worker

      - name: Publish Shrill Poetry Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: shrill-poetry-b0cc
          directory: shrill-poetry-b0cc
          command: deploy shrill-poetry-b0cc/src/index.js  # Specify the entry point for Shrill Poetry Worker
