name: Deploy Worker

on:
  push:
  pull_request:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build & Deploy Gentle Rain Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
        working-directory: gentle-rain-da08

      - name: Build & Deploy Shrill Poetry Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
        working-directory: shrill-poetry-b0cc
